### ISSUE TITLE
DB OperationalError during migration when adding a Country foreignkey to an existing model

### ISSUE THREAD

**Issue by DanyPM** [cordery/django-countries-plus#20]
Hi back mates !
Thanks for the (very) quick fix to my latest issue, I am unfortunately coming to you with a new one ...

I am trying to migrate my models from django-countries to django-countries-plus.
I have a Company model with a "country" CountryField from django-countries. I am now adding a Country foreignkey "new_country".

```
from countries_plus.models import Country
from django_countries.fields import CountryField  # pragma: no cover

class Company(models.Model):  # pragma: no cover
   ....
    country = CountryField(blank=True)
    new_country = models.ForeignKey(Country, blank=True, null=True, on_delete=models.SET_NULL) # added during new migration
```

The migration file appears to show the right instructions:

```
    dependencies = [
        ('countries_plus', '0006_alter_country_options'),
        ('companies', '0014_individualactor_keyword_company_is_relevant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='new_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='countries_plus.country'),
        ),
    ]
```

But the migration cannot go through, with the following logs:

```
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (3780, "Referencing column 'new_country_id' and referenced column 'iso' in foreign key constraint 'companies_company_new_country_id_1a75fd29_fk_countries' are incompatible.")
```

I have run django-countries-plus successfully in the past and processed 0006_alter_country_options on a past migration. Countries have been installed with manage.py update_countries_plus.

I am running django 4.0.3, django-countries 7.3.2, django-countries-plus 2.1.0.
Currently the mysql DB is running utf8mb4_0900_ai_ci

**Comment by cordery** [comment]
Hi DannyPM,

The migration '0006_alter_country_options' is not provided by countries_plus.  My guess is that you modified the countries_plus model or used a fork of countries_plus that provides that migration.   Either way, you probably need to reverse that migration (`python manage.py migrate countries_plus 0005`) and then remove the migration file itself.  As I don't know why you may have made it, you should make sure that nothing else in your repo depends upon that migration, such as the file you pasted a snippet of above.  You can probably replace `('countries_plus', '0006_alter_country_options'),` with `('countries_plus', '0005_auto_20160224_1804'),` safely, as long as nothing in your database depends explicitly on the changes you made in 0006_alter_country_options.

Out of curiosity why are you switching from django-countries to django-countries-plus?  When I made the package way back in 2013 I recall that django-countries was very primitive.  Now in 2022 though it looks like quite a full featured package.

**Comment by DanyPM** [comment]
Thanks for the fast response !

That's actually weird coz I actually didn't change anything in the package. I installed it from pipfile "django-countries-plus".
The `'0006_alter_country_option` migration got installed on its own, I figure from a `__latest__` instruction in the makemigrations command. I'lll try to downgrade it to 0005 and keep you posted.

I have been using django-countries for a while, but it is very frustrating that the package doesn't allow to select objects from a ManyToManyField, like this one does. It only allows for a CountryField(multiple=true) which is very inconvenient and doesn't allow for search and horizontal filtering.

**Comment by DanyPM** [comment]
root@c41de334804d:~/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/countries_plus/migrations# cat 0006_alter_country_options.py
# Generated by Django 4.0.3 on 2022-03-28 11:52

from django.db import migrations


Here is the content of `006_alter_country_options.py`

```
class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Pays', 'verbose_name_plural': 'Countries'},
        ),
    ]
```

To be honest, I don't see how this could be affectting my primary_key issue.

**Comment by cordery** [comment]
No, that doesn't look like it was cause a problem,  it looks like it appeared because Country.Meta.verbose_name was set to "Pays".   

The migration issue you are having is probably due to a mismatch that has occurred between the field types of Company.new_country and Country.iso.    Not sure how that mismatch occurred.  I installed MySQL and migrated the example_project and was able to migrate and create objects with null values for their country field without issue.

Do your mysql table definitions for those two tables look something like:

```sql
CREATE TABLE `countries_plus_country` (
  `iso` varchar(2) NOT NULL,
  `iso3` varchar(3) NOT NULL,
  `iso_numeric` int NOT NULL,
  `fips` varchar(3) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `capital` varchar(255) DEFAULT NULL,
  `area` decimal(11,2) DEFAULT NULL,
  `population` int DEFAULT NULL,
  `continent` varchar(2) DEFAULT NULL,
  `tld` varchar(255) DEFAULT NULL,
  `currency_code` varchar(3) DEFAULT NULL,
  `currency_symbol` varchar(255) DEFAULT NULL,
  `currency_name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `postal_code_format` varchar(255) DEFAULT NULL,
  `postal_code_regex` varchar(255) DEFAULT NULL,
  `languages` varchar(255) DEFAULT NULL,
  `geonameid` int DEFAULT NULL,
  `neighbours` varchar(255) DEFAULT NULL,
  `equivalent_fips_code` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`iso`),
  UNIQUE KEY `iso3` (`iso3`),
  UNIQUE KEY `iso_numeric` (`iso_numeric`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

And your related table, in my case sample_app.Company:
```sql
CREATE TABLE `sample_app_company` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(512) NOT NULL,
  `country_id` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sample_app_company_country_id_9fcabe3b_fk_countries` (`country_id`),
  CONSTRAINT `sample_app_company_country_id_9fcabe3b_fk_countries` FOREIGN KEY (`country_id`) REFERENCES `countries_plus_country` (`iso`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

**Comment by DanyPM** [comment]
Hi !

I just tried a new migration and got the create statement for both tables:

```
CREATE TABLE `countries_plus_country` (
  `iso` varchar(2) NOT NULL,
  `iso3` varchar(3) NOT NULL,
  `iso_numeric` int NOT NULL,
  `fips` varchar(3) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `capital` varchar(255) DEFAULT NULL,
  `area` decimal(11,2) DEFAULT NULL,
  `population` int DEFAULT NULL,
  `continent` varchar(2) DEFAULT NULL,
  `tld` varchar(255) DEFAULT NULL,
  `currency_code` varchar(3) DEFAULT NULL,
  `currency_symbol` varchar(255) DEFAULT NULL,
  `currency_name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `postal_code_format` varchar(255) DEFAULT NULL,
  `postal_code_regex` varchar(255) DEFAULT NULL,
  `languages` varchar(255) DEFAULT NULL,
  `geonameid` int DEFAULT NULL,
  `neighbours` varchar(255) DEFAULT NULL,
  `equivalent_fips_code` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`iso`),
  UNIQUE KEY `iso3` (`iso3`),
  UNIQUE KEY `iso_numeric` (`iso_numeric`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```


```
CREATE TABLE `companies_company` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `country` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `keywords` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `presentation` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `tech` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ceo` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_count` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sales` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone_number` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `website` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `stakeholders` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `exportation` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `public_partners` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `international_partners` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `private_partners` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `french_partners` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `company_type_id` int DEFAULT NULL,
  `banner` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `logo` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_free` tinyint(1) NOT NULL,
  `completion_score` int NOT NULL,
  `date_modified` datetime(6) NOT NULL,
  `internal_notes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `remarks` varchar(35) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `published` tinyint(1) NOT NULL,
  `GMaps_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_relevant` tinyint(1) NOT NULL,
  `new_employee_count` bigint unsigned DEFAULT NULL,
  `new_phone_number` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `new_sales` decimal(14,2) DEFAULT NULL,
  `new_sales_currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ready_to_migrate` tinyint(1) NOT NULL,
  `new_ceo_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `companies_company_company_type_id_adb43e18_fk_companies` (`company_type_id`),
  KEY `companies_company_new_ceo_id_0546a2ab_fk_companies` (`new_ceo_id`),
  CONSTRAINT `companies_company_company_type_id_adb43e18_fk_companies` FOREIGN KEY (`company_type_id`) REFERENCES `companies_companytype` (`id`),
  CONSTRAINT `companies_company_new_ceo_id_0546a2ab_fk_companies` FOREIGN KEY (`new_ceo_id`) REFERENCES `companies_individualactor` (`id`),
  CONSTRAINT `companies_company_chk_1` CHECK ((`new_employee_count` >= 0))
) ENGINE=InnoDB AUTO_INCREMENT=2890 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
These two statements ahve been generated AFTER the migration attempt with the new_country FK.

I get the following error during migration :

`django.db.utils.OperationalError: (3780, "Referencing column 'new_country_id' and referenced column 'iso' in foreign key constraint 'companies_company_new_country_id_1a75fd29_fk_countries' are incompatible.")`

I just checked and apparently the migration on an empty `companies_company` table actually works.
It is the migration of the actual data I have (about 2k lines) that triggers the error. I really don't get how that could be

**Comment by cordery** [comment]
Found the solution:

After some digging I came across these [stackoverflow](https://stackoverflow.com/questions/58550408/error-when-foreign-referencing-in-mysql-error-3780) [questions](https://stackoverflow.com/questions/1457305/mysql-creating-tables-with-foreign-keys-giving-errno-150/4673775#4673775) which lead me to believe that the issue is that the two tables/fields do not have the same character set and/or collation.  

I noticed that your companies_company table and your countries_plus_country table have the same charset `utf8mb4`, but they have different collation `utf8mb4_unicode_ci` vs `utf8mb4_0900_ai_ci`.  

According to the [mysql docs](https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html) the default collation is now `utf8mb4_0900_ai_ci` with more information provided [here](https://dev.mysql.com/blog-archive/new-collations-in-mysql-8-0-0/).  

To solve your problem, either:
- convert either the countries_plus_country table to use the older `utf8mb4_unicode_ci` collation that your company table is using
- or perhaps preferably, convert your company table to use the new `utf8mb4_0900_ai_ci` collation that the countries_plus table is using (and any other new tables in your database)

For example, running the following would fix the issue by converting your company table:
`alter table companies_company CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci`

This was a good lesson on the perils of using a charfield as a primary key!  Sorry about all the trouble.  I'll update the Readme with this issue on the next release.

**Comment by DanyPM** [comment]
Hey ! Sorry for the delay.
I just successfully converted my tables and migrated the Country field. It was indeed a collation incompatibility.

Thank you so much for the work and extensive amount of research invested in solving this issue.

Sincerely
