### ISSUE TITLE
Change gettext to gettext_lazy in Country model

### ISSUE THREAD

**Issue by Ivan-Vinitskyi** [cordery/django-countries-plus#28]
In general it is better to use `gettext_lazy`:
https://github.com/cordery/django-countries-plus/blob/1eb0a0b61c83669224c33952b3fb4096c83cb587/countries_plus/models.py#L6C38-L6C45

**Comment by kissgyorgy** [comment]
This is causing Exceptions with Django 5:
```
AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready.
```
