### ISSUE TITLE
phone field is too short: psycopg2.DataError: value too long for type character varying(5)

### ISSUE THREAD

**Issue by blueyed** [cordery/django-countries-plus#7]
I am seeing the following error when running the `update_countries_plus` command:

    Traceback (most recent call last):
      File "…/pyenv/project/lib/python3.4/site-packages/django/db/backends/utils.py", line 67, in execute
        return self.cursor.execute(sql, params)
    psycopg2.DataError: value too long for type character varying(5)

    sql:
    UPDATE "countries_plus_country" SET "iso3" = %s, "iso_numeric" = %s, "fips" = %s, "name" = %s, "capital" = %s, "area" = %s, "population" = %s, "continent" = %s, "tld" = %s, "currency_code" = %s, "currency_symbol" = %s, "currency_name" = %s, "phone" = %s, "postal_code_format" = NULL, "postal_code_regex" = NULL, "languages" = %s, "geoname id" = %s, "neighbours" = %s, "equivalent_fips_code" = NULL WHERE "countries_plus_country"."iso" = %s

    params:
    ('ATG', 28, 'AC', 'Antigua and Barbuda', "St. John's", '443.0', 86754, 'NA', '.ag', 'XCD', '$', 'Dollar', '+1-268', 'en-AG', 3576396, '', 'AG')

The "varying(5)" field seems to be `phone`, and the value here is `'+1-268'`.

**Comment by blueyed** [comment]
Turns out that a length of `16` would be required (currently).

The longest entry is `'+1-809 and 1-829'` for 'Dominican Republic'.

Not sure if that's supposed to be a valid value for this field?!
Maybe it should be converted to '+1-809,+1-829'?

**Comment by cordery** [comment]
I forgot (again) that sqlite does not enforce the lengths of a varchar, and neither does django on object save() (https://docs.djangoproject.com/en/dev/ref/models/instances/#id1).  When I originally wrote the model definition I had incorrect ideas about the need to limit varchars.  In fact, for most databases the actual size of the internal field is the length of the longest value, regardless if the limit is set higher.  So varchar(255) takes the same amount of disk space as varchar(2) assuming the longest string is 2 characters long.  I am going to alter the model to increase the size of varchar fields for non fixed length fields (ie I will not change the iso, iso3, fips, or other columns which have actual definitions for their field length).  I will however force the model to call full_clean on save, which will catch overflowing varchars and raise a GeonamesParseError.  

I see Puerto Rico also has an "and" value, I'll convert them to comma separated on import as you suggested.

**Comment by cordery** [comment]
Fixed in 9d865935a5c2384af5dcda751aeff4a62f166769

**Comment by blueyed** [comment]
Awesome, thanks!
