### ISSUE TITLE
Geonames file format change?

### ISSUE THREAD

**Issue by kskumar** [cordery/django-countries-plus#8]
Tried running `python manage.py update_countries_plus` today in a new project and ran into the following error:

`countries_plus.utils.GeonamesParseError: I couldn't parse the Geonames file (http://download.geonames.org/export/dump/countryInfo.txt).  The format may have changed. An updated version of this software may be required, please check for updates and/or raise an issue on github.  Specific error: Unexpected field length: {'area': [u'Ensure that there are no more than 1 decimal place.']}`

This error also exists in other projects where `update_countries_plus` previously worked without issue.

All of the projects (the new one + the old ones) are using v1.0.1 from pip.

**Comment by CelloPt** [comment]
Hello!

I have a fix for it. I wanted to upload the fix to a branch and then issue a PR.

@cordery can I help you solve this?

**Comment by cordery** [comment]
Absolutely!  Would very much appreciate a PR.
